---
title: "Projekt_3"
author: "Kamil Sarzyniak, Piotr Stawarski"
date: '2024-11-06'
output: pdf
---

```{r}
library(forecast)
library(tseries)
library(MASS)
library(ggplot2)
library(tidyr)
```

```{r}
n_values <- c(50, 100, 1000)
ar_values <- c(.1, .5, .9)
n_reps <- 1000
results <- vector("list", n_reps)
```

```{r}
n_values <- c(50, 100, 1000)
ar_values <- c(.1, .5, .9)

for (rep in 1:n_reps) {
  rep_results <- list()
  
  for (N in n_values) {
      estimates <- matrix(NA, nrow = N, ncol = 3)
      stderrs <- matrix(NA, nrow = N, ncol = 3)
      residual_acf <- matrix(NA, nrow = N, ncol = 20)
      i <- 1
    
      for (AR in ar_values) {
        xt1 = arima.sim(list(order=c(1,0,0), ar=AR), n=N)
        
        xt3 = Arima(xt1, order = c(3,0,0))
        
        estimates[i, ] <- xt3$coef[1:3]
        stderrs[i, ] <- sqrt(diag(xt3$var.coef))[1:3]
        residual_acf[i, ] <- acf(residuals(xt3), plot = FALSE)$acf[2:21]
        i <- i + 1
      }
      rep_results[[paste0("N_", N)]] <- list(
      estimates = estimates,
      stderrs = stderrs,
      residual_acf = residual_acf
    )
  }
  results[[rep]] <- rep_results
}
```

```{r}
combine_estimates <- function(results, N) {
  do.call(rbind, lapply(results, function(rep) rep[[N]]$estimates))
}
```

```{r}
summarize_estimates <- function(estimates_all, true_params) {
  mean_estimates <- colMeans(estimates_all, na.rm = TRUE)
  bias <- mean_estimates - true_params
  sd_estimates <- apply(estimates_all, 2, sd, na.rm = TRUE)
  
  data.frame(
    Parameter = paste0("AR", 1:3),
    Mean = mean_estimates,
    Bias = bias,
    SD = sd_estimates
  )
}
```

```{r}
analyze_all <- function(results, true_params) {
  summary_list <- list()
  
  for (N in names(results[[1]])) {
    estimates_all <- combine_estimates(results, N)
    summary_list[[N]] <- summarize_estimates(estimates_all, true_params)
  }
  
  return(summary_list)
}
```

```{r}
display_summary <- function(summary_results) {
  for (N in names(summary_results)) {
    cat(paste0("Długość danych: ", N, "\n"))
    print(summary_results[[N]])
    cat("\n")
  }
}
```

```{r}
combine_estimates_for_N <- function(results, N) {
  estimates_all <- do.call(rbind, lapply(results, function(rep) rep[[N]]$estimates))
  colnames(estimates_all) <- paste0("AR", 1:3)
  return(estimates_all)
}
```

```{r}
prepare_data_for_plot <- function(estimates_all) {
  estimates_df <- data.frame(estimates_all)
  estimates_df_long <- estimates_df %>%
    pivot_longer(cols = everything(), names_to = "variable", values_to = "value")
  return(estimates_df_long)
}
```

```{r}
plot_histograms <- function(estimates_df_long) {
  ggplot(estimates_df_long, aes(x = value)) +
    geom_histogram(bins = 30, color = "black", fill = "skyblue", alpha = 0.7) +
    facet_wrap(~variable, scales = "free", ncol = 1) +
    theme_minimal() +
    labs(
      title = "Rozkład estymatorów parametrów AR(3) przy danych z AR(1)",
      x = "Wartość estymatora",
      y = "Częstość"
    )
}
```

```{r}
# Podsumowanie wyników
true_params <- c(.1, .5, .9)  # Prawdziwe parametry AR(1)
summary_results <- analyze_all(results, true_params)

# Wyświetlanie podsumowania
display_summary(summary_results)

# Analiza dla konkretnej długości danych (N=1000)
N_focus <- "N_50"
estimates_all <- combine_estimates_for_N(results, N_focus)

# Przygotowanie danych do wykresów
estimates_df_long <- prepare_data_for_plot(estimates_all)

# Tworzenie histogramów N_50
plot_histograms(estimates_df_long)
```

```{r}
# Podsumowanie wyników
true_params <- c(.1, .5, .9)  # Prawdziwe parametry AR(1)
summary_results <- analyze_all(results, true_params)

# Wyświetlanie podsumowania
display_summary(summary_results)

# Analiza dla konkretnej długości danych (N=1000)
N_focus <- "N_100"
estimates_all <- combine_estimates_for_N(results, N_focus)

# Przygotowanie danych do wykresów
estimates_df_long <- prepare_data_for_plot(estimates_all)

# Tworzenie histogramów N_50
plot_histograms(estimates_df_long)
```

```{r}
# Podsumowanie wyników
true_params <- c(.1, .5, .9)  # Prawdziwe parametry AR(1)
summary_results <- analyze_all(results, true_params)

# Wyświetlanie podsumowania
display_summary(summary_results)

# Analiza dla konkretnej długości danych (N=1000)
N_focus <- "N_1000"
estimates_all <- combine_estimates_for_N(results, N_focus)

# Przygotowanie danych do wykresów
estimates_df_long <- prepare_data_for_plot(estimates_all)

# Tworzenie histogramów N_50
plot_histograms(estimates_df_long)
```

```{r}
generate_ar3_data <- function(N, params = c(0.1, 0.5, 0.3)) {
  arima.sim(list(order = c(3, 0, 0), ar = params), n = N)
}
```

```{r}
fit_ar1 <- function(data) {
  Arima(data, order = c(1, 0, 0))
}
```

```{r}
analyze_single_simulation <- function(N, params = c(0.1, 0.5, 0.3)) {
  estimates <- matrix(NA, nrow = 1, ncol = 1)
  stderrs <- matrix(NA, nrow = 1, ncol = 1)
  residual_acf <- matrix(NA, nrow = 1, ncol = 20)
  
  # Generacja danych i dopasowanie modelu
  xt_ar3 <- generate_ar3_data(N, params)
  xt_ar1 <- fit_ar1(xt_ar3)
  
  # Zapisywanie wyników
  estimates[1, ] <- xt_ar1$coef[1]
  stderrs[1, ] <- sqrt(diag(xt_ar1$var.coef))[1]
  residual_acf[1, ] <- acf(residuals(xt_ar1), plot = FALSE)$acf[2:21]
  
  return(list(estimates = estimates, stderrs = stderrs, residual_acf = residual_acf))
}
```

```{r}
run_simulation_ar3_to_ar1 <- function(n_values, n_reps, params = c(0.1, 0.5, 0.3)) {
  results <- vector("list", n_reps)
  
  for (rep in 1:n_reps) {
    rep_results <- list()
    for (N in n_values) {
      rep_results[[paste0("N_", N)]] <- analyze_single_simulation(N, params)
    }
    results[[rep]] <- rep_results
  }
  
  return(results)
}
```

```{r}
# Parametry symulacji
n_values <- c(50, 100, 1000)
n_reps <- 1000
ar3_params <- c(0.1, 0.5, 0.3)

# Uruchomienie symulacji
results_ar3_to_ar1 <- run_simulation_ar3_to_ar1(n_values, n_reps, ar3_params)
```

```{r}
get_estimates_ar1 <- function(results, N) {
  do.call(rbind, lapply(results, function(rep) rep[[N]]$estimates))
}
```

```{r}
compute_statistics_ar1 <- function(estimates, true_param) {
  mean_estimates <- colMeans(estimates, na.rm = TRUE)
  bias <- mean_estimates - true_param
  sd_estimates <- apply(estimates, 2, sd, na.rm = TRUE)
  
  data.frame(
    Parameter = "AR1",
    Mean = mean_estimates,
    Bias = bias,
    SD = sd_estimates
  )
}
```

```{r}
analyze_results_ar3_to_ar1 <- function(results, true_param) {
  summary_list <- list()
  
  for (N in names(results[[1]])) {
    estimates_all <- get_estimates_ar1(results, N)
    summary_list[[N]] <- compute_statistics_ar1(estimates_all, true_param)
  }
  
  return(summary_list)
}
```

```{r}
print_summary_ar3_to_ar1 <- function(summary_results) {
  for (N in names(summary_results)) {
    cat(paste0("Długość danych: ", N, "\n"))
    print(summary_results[[N]])
    cat("\n")
  }
}
```

```{r}
# Parametry
true_param_ar1 <- 0.1  # Prawdziwa wartość parametru AR(1)

# Analiza wyników
summary_results_ar3_to_ar1 <- analyze_results_ar3_to_ar1(results_ar3_to_ar1, true_param_ar1)

# Wyświetlenie wyników
print_summary_ar3_to_ar1(summary_results_ar3_to_ar1)
```

